---
title: "Use_gmr_to_Run_GMACS"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Use_gmr_to_Run_GMACS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo=FALSE,message=FALSE,warning=FALSE,
  eval=FALSE
)
```

```{r setup, echo=TRUE}

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))


# Some functions used to run admb in R
# install.packages("PBSadmb")
library(PBSadmb)
library(knitr)
library(svDialogs)
library(miceadds)

library(gmr)
```

```{r Define runs and versions, echo=TRUE, message=FALSE, warning=FALSE, include=FALSE}

# Species of interest
.Spc <-c(
  # "SMBKC"
  "all"
  # "WAG",
  # "EAG"
  )

# Names of the GMACS version to consider for run
.GMACS_version <- c(
  "Dvpt_Version",
  "Latest_Version"
  )

# Define directory
# /!\ If the last assessment is used here, the directory for this 
# folder will be: paste0(dirname(getwd()), "/Assessments/")

.VERSIONDIR <- c(
  paste0(getwd(), "/Dvpt_Version/"),
  paste0(getwd(), "/Latest_Version/")
)

# Use Last Assessment for comparison?
# If yes, you must provide the names of the model for each species in the variable .ASSMOD_NAMES
# Those model folder must have to be hold in the folder Assessments
.ASS <- FALSE

# names of the model for the last assessment - Only useful if comparison is made.
# if all stocks are considered they have to be ordered as follow:
# "AIGKC/EAG" / "AIGKC/WAG" / "BBRKC" / "SMBKC" / "SNOW"
.ASSMOD_NAMES <- NULL
                # c("model_21_1e",
                #   "model_21_1e",
                #   "model_21_1",
                #   "model_16_0",
                #   "model_21_g")

# Need to conpile the model?
  # vector of length(.GMACS_version)
  # 0: GMACS is not compiled. This assumes that an executable exists in the directory of the concerned version.
  # 1: GMACS is compiles
.COMPILE <- c(1,1)

# Run GMACS
.RUN_GMACS <- TRUE

# Use latets available data for the assessment?
.LastAssDat <- TRUE

# Define the directories for ADMB
.ADMBpaths <- "ADpaths.txt"


# Do comparison?
.MAKE_Comp <- TRUE

# Show Rterminal
.VERBOSE <- TRUE

```

```{r, echo=TRUE, results='asis'}


# source("Run_GMACS_Function.R")
source("Additional_functions.R")

res <- GMACS(
  Spc = .Spc,
  GMACS_version = .GMACS_version,
  Dir = .VERSIONDIR,
  ASS = .ASS,
  AssMod_names = .ASSMOD_NAMES,
  compile = .COMPILE,
  run = .RUN_GMACS,
  LastAssDat = .LastAssDat,
  ADMBpaths = .ADMBpaths,
  make.comp = .MAKE_Comp,
  verbose <- .VERBOSE
)

```
