---
title: "Use gmr to Run GMACS"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Use gmr to Run GMACS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo=FALSE,message=FALSE,warning=FALSE,
  eval=FALSE
)
```

```{r setup, echo=TRUE}

# I- Install/Update gmr and load packages ----

rm(list = ls())     # Clean your R session

# Set the working directory as the directory of this document
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

# check your directory
getwd()

# Install and load the packages

# 1.Install devtools and gdata on your machine
if (!require("devtools")) {
  # install devtools
  install.packages("devtools")
}

if (!require("gdata")) {
  # needed to manipulate data
  install.packages("gdata")
}

# 2. Install / update gmr package
Src <- "GMACS-project/gmr"
# Get the latest version of gmr? (0: no; 1: install for the first time; 2: update the package)
Update <-
  0
# Inidicate the library directory to remove the gmr package from
mylib <-
  "~/R/win-library/4.1"

#  remotes::install_github() will work to install gmr on your machine
if (Update == 1)
  devtools::install_github(Src)

# Updating to the latest version of gmr
if (Update == 2) {
  remove.packages("gmr", lib = mylib)
  devtools::install_github(Src)
}

# Load the gmr package
library(gmr)
# -----------------------------------------------------------


```

```{r Compile GMACS, echo=TRUE, message=FALSE, warning=FALSE, include=FALSE}

# II- Compile and build GMACS ----

# Set the working directories:
Dir_Dvpt_Vers <- file.path(here::here(), "Dvpt_Version")
Dir_Last_Vers <- file.path(here::here(), "Latest_Version")

# Define the name of the file containing the different pathways needed to build
# the GMACS executable - The ADpaths_Windows.txt file has to be used for windows
# machine and the ADpaths_MacOS.txt for Linux-like machine (including MacOS)
# /!\ his file need to be modified so the paths will fit to your machine
ADMBpaths <- ifelse(.Platform$OS.type == "windows",
                    "ADpaths_Windows.txt",
                    "ADpaths_MacOS.txt")

# Now run the createGmacsExe() function to get the executable for the
# latest version (if applicable)
createGmacsExe(
  vv = 2,
  Dir = c(Dir_Dvpt_Vers, Dir_Last_Vers),
  verbose = FALSE,
  ADMBpaths = ADMBpaths
)
# -----------------------------------------------------------

```



```{r Define runs and versions, echo=TRUE, message=FALSE, warning=FALSE, include=FALSE}

# Define the working directories

# Stock of interest - Here we are going to test all stocks
# Vector of character string
# For one stock in particular (e.g., EAG), use the following command:
# Stock <-c(
#   "EAG","WAG"
# )
Stock <-c(
  # "SMBKC", "EAG"
  "all"
)

# Names of the GMACS version to consider
# Character string
# Here we focus on the development version ("Dvpt_Version")
GMACS_version <- c(
  "Latest_Version"
)

# Define directories (path to the version you are working on)
# Character string 
VERSIONDIR <- Dir_Last_Vers

# Use Last Assessment for comparison?
# Logical
# If yes, you must provide the names of the model(s) you want to consider for 
# comparison for each stock in the variable named ASSMOD_NAMES. 
# Those models folders must have to be hold in the "Assessments" folder of 
# the GMACS_Assessment_code repository.
ASS <- FALSE

# Do ou need to compile GMACS?
# vector of interger of length(.GMACS_version)
# 0: GMACS does not need to be compiled. This assumes that an executable exists in the directory of the concerned version.
# 1: GMACS needs to be compiled
COMPILE <- 0       # You already compile and build the executable

# Run GMACS
# Logical
# Here, we want to get an assessment for each stock
RUN_GMACS <- TRUE

# Use latest available data for the assessment?
# Logical
# If TRUE, the model will be using the input files available in the "Assessment_data"
# folder of the GMACS_Assessment_code repository. 
# Remind that if you implemented a version in which you made modifications on the
# input files (either the .ctl, .dat, or .prj files) you don't want to use the 
# original files because it won't work.
LastAssDat <- FALSE

# Show Rterminal
# Do you want to see what is going on? (similar to verbose <- TRUE)
# Logical
VERBOSE <- TRUE

# Do comparisons?
# Logical
# This is not the topic right now
MAKE_Comp <- FALSE

```

```{r, echo=TRUE, results='asis'}

res <- GMACS(
  Spc = Stock,
  GMACS_version = GMACS_version,
  Dir = VERSIONDIR,
  ASS = ASS,
  compile = COMPILE,
  run = RUN_GMACS,
  LastAssDat = LastAssDat,
  ADMBpaths = ADMBpaths,
  make.comp = MAKE_Comp,
  verbose = VERBOSE,
  cleanOut = TRUE
)

```
