on:
  push:
    paths:
      - 'R/**'
      - 'README.Rmd'

name: update-pkgdown-site

jobs:
  update-pkgdown-site:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install packages
        run: |
          install.packages(c("PBSadmb","pkgdown", "roxygen2", "ggplot2", "knitr", "here", "dplyr", "kableExtra"))
        shell: Rscript {0}

      - name: Update documentation
        run: |
          roxygen2::roxygenize()
        shell: Rscript {0}

      - name: Update README.md
        run: |
          knitr::knit("README.md")
        shell: Rscript {0}

      - name: Build site
        run: |
          pkgdown::build_site()
        shell: Rscript {0}

      - name: Set up Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
      - name: Commit all changes
        run: |
          git add -A && git commit -m 'Build site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
